In [1]:
# Load the important libraries

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

In [2]:
# Load the dataframe

df = pd.read_csv(r"d:\my multiple projects\end to end ecomerce sales project\ecommerce_dataset.csv")

df.head()

,Order_ID,Customer_ID,Customer_Name,Gender,Age,Email,Phone_Number,Country,State,City,...,Return_Reason,Refund_Amount,Customer_Rating,Review_Count,Customer_Segment,Device_Type,Traffic_Source,Session_ID,Currency,Sales_Channel
0,ORD-88FF38794E07,CUST-BAE0BD6348,Akari Suzuki,Female,42,akari.suzuki256@yahoo.com,+81-45-2750-6143,Japan,Kanagawa,Yokohama,...,NaN,0.0,2.0,2.0,Loyal,Mobile,Social Media,SESS-4FBB304AFCB6B09D,JPY,Marketplace
1,ORD-D70F739244DC,CUST-C5E61814B8,Mia Muller,Female,21,mia.muller200@outlook.com,+49-89-1138957,Germany,Bavaria,Munich,...,NaN,0.0,NaN,1.0,Regular,Desktop,Paid Ads,NaN,EUR,Mobile App
2,ORD-0736933B19D9,CUST-B0E1277A55,Yui Tanaka,Female,36,yui.tanaka243@outlook.com,NaN,Japan,Tokyo,Tokyo,...,NaN,0.0,5.0,4.0,VIP,Mobile,Paid Ads,SESS-DC0407EB60C861EA,JPY,Website
3,ORD-6C2256E4BDE1,CUST-BBE0126482,Joseph Brown,Male,40,joseph.brown471@gmail.com,+1-777-264-8779,United States,Texas,Houston,...,NaN,0.0,3.0,NaN,Regular,NaN,Referral,SESS-ED055BE40774EBE0,USD,Marketplace
4,ORD-214B965CFE20,CUST-780BA168E6,Alexander Becker,Male,37,alexander.becker10@hotmail.com,+49-221-7224982,Germany,North Rhine-Westphalia,Cologne,...,NaN,0.0,5.0,4.0,Regular,Desktop,Social Media,SESS-83DC07B990A90D4D,EUR,Website

In [3]:
# Check the size of the dataset

df.shape

(109884, 49)

In [4]:
# understand the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109884 entries, 0 to 109883
Data columns (total 49 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             109884 non-null  object
 1   Customer_ID          109884 non-null  object
 2   Customer_Name        109884 non-null  object
 3   Gender               109884 non-null  object
 4   Age                  109884 non-null  int64
 5   Email                109884 non-null  object
 6   Phone_Number         95588 non-null   object
 7   Country              109884 non-null  object
 8   State                109884 non-null  object
 9   City                 109884 non-null  object
 10  Postal_Code          96253 non-null   object
 11  Registration_Date    109884 non-null  object
 12  Order_Date           109884 non-null  object
 13  Shipping_Date        86161 non-null   object
 14  Delivery_Date        83184 non-null   object
 15  Product_ID           109884 non-null  object
 16  SKU                  109884 non-null  object
 17  Product_Name         109884 non-null  object
 18  Category             109884 non-null  object
 19  Sub_Category         109884 non-null  object
 20  Brand                109884 non-null  object
 21  Unit_Price           109884 non-null  float64
 22  Quantity             109884 non-null  int64
 23  Discount_Percentage  96987 non-null   float64
 24  Discount_Amount      109884 non-null  float64
 25  Tax                  109884 non-null  float64
 26  Shipping_Cost        109884 non-null  float64
 27  Cost                 109884 non-null  float64
 28  Profit               109884 non-null  float64
 29  Total_Amount         109884 non-null  float64
 30  Payment_Method       109884 non-null  object
 31  Payment_Status       109884 non-null  object
 32  Order_Status         109884 non-null  object
 33  Delivery_Method      109884 non-null  object
 34  Warehouse            109884 non-null  object
 35  Seller_ID            109884 non-null  object
 36  Seller_Name          97277 non-null   object
 37  Coupon_Code          34356 non-null   object
 38  Returned             109884 non-null  object
 39  Return_Reason        9352 non-null    object
 40  Refund_Amount        109884 non-null  float64
 41  Customer_Rating      95876 non-null   float64
 42  Review_Count         95413 non-null   float64
 43  Customer_Segment     109884 non-null  object
 44  Device_Type          94296 non-null   object
 45  Traffic_Source       96285 non-null   object
 46  Session_ID           97457 non-null   object
 47  Currency             109884 non-null  object
 48  Sales_Channel        109884 non-null  object
dtypes: float64(11), int64(2), object(36)
memory usage: 41.1+ MB

In [5]:
# Understand the datset with a quick statistics

df.describe()

,Age,Unit_Price,Quantity,Discount_Percentage,Discount_Amount,Tax,Shipping_Cost,Cost,Profit,Total_Amount,Refund_Amount,Customer_Rating,Review_Count
count,109884.000000,109884.000000,109884.000000,96987.000000,109884.000000,109884.000000,109884.000000,109884.000000,109884.000000,109884.000000,109884.000000,95876.000000,95413.000000
mean,33.560409,165.888690,2.279176,6.686360,25.467878,49.991356,4.337459,198.187184,150.019583,406.873041,37.421502,4.002754,3.006991
std,9.567190,325.823042,1.606851,9.023796,112.765016,134.801476,5.721675,568.885902,343.447369,1016.372438,313.060736,1.112795,1.738545
min,16.000000,3.020000,1.000000,0.000000,0.000000,0.140000,0.000000,1.140000,-480.250000,2.280000,0.000000,1.000000,0.000000
25%,27.000000,10.050000,1.000000,0.000000,0.000000,2.210000,0.000000,7.830000,2.020000,27.520000,0.000000,3.000000,2.000000
50%,33.000000,37.130000,2.000000,5.000000,0.160000,8.650000,2.720000,28.490000,27.360000,81.110000,0.000000,4.000000,3.000000
75%,40.000000,154.740000,3.000000,10.000000,7.810000,35.052500,5.250000,111.420000,138.900000,296.152500,0.000000,5.000000,4.000000
max,84.000000,1962.140000,10.000000,40.000000,5550.240000,3567.020000,23.610000,12974.850000,6347.230000,22340.820000,18228.210000,5.000000,13.000000

In [6]:
# Understand the categorical columns with statistics

df.describe(include=object)

,Order_ID,Customer_ID,Customer_Name,Gender,Email,Phone_Number,Country,State,City,Postal_Code,...,Seller_Name,Coupon_Code,Returned,Return_Reason,Customer_Segment,Device_Type,Traffic_Source,Session_ID,Currency,Sales_Channel
count,109884,109884,109884,109884,109884,95588,109884,109884,109884,96253,...,97277,34356,109884,9352,109884,94296,96285,97457,109884,109884
unique,101203,13898,1852,2,13874,13500,10,45,52,9423,...,60,10,2,7,3,3,6,89734,9,4
top,ORD-02753BD52813,CUST-CE60C3192B,Thomas Smith,Male,richard.davis148@gmail.com,+55-11-91330-3610,United States,England,Chicago,77091,...,Seller Co #30,SAVE15,No,Late Delivery,VIP,Mobile,Organic Search,SESS-9E4BA37A62453FD7,USD,Website
freq,4,84,371,55969,84,79,24693,6499,4436,136,...,1686,3532,98996,1369,39967,54479,26964,4,24693,49297

In [7]:
# Inspect missing records

In [8]:
df.isnull().sum()

Order_ID                    0
Customer_ID                 0
Customer_Name               0
Gender                      0
Age                         0
Email                       0
Phone_Number            14296
Country                     0
State                       0
City                        0
Postal_Code             13631
Registration_Date           0
Order_Date                  0
Shipping_Date           23723
Delivery_Date           26700
Product_ID                  0
SKU                         0
Product_Name                0
Category                    0
Sub_Category                0
Brand                       0
Unit_Price                  0
Quantity                    0
Discount_Percentage     12897
Discount_Amount             0
Tax                         0
Shipping_Cost               0
Cost                        0
Profit                      0
Total_Amount                0
Payment_Method              0
Payment_Status              0
Order_Status                0
Delivery_Method             0
Warehouse                   0
Seller_ID                   0
Seller_Name             12607
Coupon_Code             75528
Returned                    0
Return_Reason          100532
Refund_Amount               0
Customer_Rating         14008
Review_Count            14471
Customer_Segment            0
Device_Type             15588
Traffic_Source          13599
Session_ID              12427
Currency                    0
Sales_Channel               0
dtype: int64

In [9]:
# Inspect missing records in percentage

missing_records_percentage = (df.isnull().sum() / len(df) ) * 100

missing_records_percentage

Order_ID                0.000000
Customer_ID             0.000000
Customer_Name           0.000000
Gender                  0.000000
Age                     0.000000
Email                   0.000000
Phone_Number           13.010083
Country                 0.000000
State                   0.000000
City                    0.000000
Postal_Code            12.404900
Registration_Date       0.000000
Order_Date              0.000000
Shipping_Date          21.589130
Delivery_Date          24.298351
Product_ID              0.000000
SKU                     0.000000
Product_Name            0.000000
Category                0.000000
Sub_Category            0.000000
Brand                   0.000000
Unit_Price              0.000000
Quantity                0.000000
Discount_Percentage    11.736923
Discount_Amount         0.000000
Tax                     0.000000
Shipping_Cost           0.000000
Cost                    0.000000
Profit                  0.000000
Total_Amount            0.000000
Payment_Method          0.000000
Payment_Status          0.000000
Order_Status            0.000000
Delivery_Method         0.000000
Warehouse               0.000000
Seller_ID               0.000000
Seller_Name            11.473008
Coupon_Code            68.734302
Returned                0.000000
Return_Reason          91.489207
Refund_Amount           0.000000
Customer_Rating        12.747989
Review_Count           13.169342
Customer_Segment        0.000000
Device_Type            14.185869
Traffic_Source         12.375778
Session_ID             11.309199
Currency                0.000000
Sales_Channel           0.000000
dtype: float64

In [10]:
# Standarize the column names

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

df.columns

Index(['order_id', 'customer_id', 'customer_name', 'gender', 'age', 'email',
       'phone_number', 'country', 'state', 'city', 'postal_code',
       'registration_date', 'order_date', 'shipping_date', 'delivery_date',
       'product_id', 'sku', 'product_name', 'category', 'sub_category',
       'brand', 'unit_price', 'quantity', 'discount_percentage',
       'discount_amount', 'tax', 'shipping_cost', 'cost', 'profit',
       'total_amount', 'payment_method', 'payment_status', 'order_status',
       'delivery_method', 'warehouse', 'seller_id', 'seller_name',
       'coupon_code', 'returned', 'return_reason', 'refund_amount',
       'customer_rating', 'review_count', 'customer_segment', 'device_type',
       'traffic_source', 'session_id', 'currency', 'sales_channel'],
      dtype='object')

In [11]:
# Investigate the datatypes

df.dtypes

order_id                object
customer_id             object
customer_name           object
gender                  object
age                      int64
email                   object
phone_number            object
country                 object
state                   object
city                    object
postal_code             object
registration_date       object
order_date              object
shipping_date           object
delivery_date           object
product_id              object
sku                     object
product_name            object
category                object
sub_category            object
brand                   object
unit_price             float64
quantity                 int64
discount_percentage    float64
discount_amount        float64
tax                    float64
shipping_cost          float64
cost                   float64
profit                 float64
total_amount           float64
payment_method          object
payment_status          object
order_status            object
delivery_method         object
warehouse               object
seller_id               object
seller_name             object
coupon_code             object
returned                object
return_reason           object
refund_amount          float64
customer_rating        float64
review_count           float64
customer_segment        object
device_type             object
traffic_source          object
session_id              object
currency                object
sales_channel           object
dtype: object

In [12]:
# Standarize the data types

df["order_date"] = pd.to_datetime(df["order_date"])

df["shipping_date"] = pd.to_datetime(df["shipping_date"])

df["delivery_date"] = pd.to_datetime(df["delivery_date"])

Handle missing records

In [13]:
# Detect missing records
df.isnull().sum()

order_id                    0
customer_id                 0
customer_name               0
gender                      0
age                         0
email                       0
phone_number            14296
country                     0
state                       0
city                        0
postal_code             13631
registration_date           0
order_date                  0
shipping_date           23723
delivery_date           26700
product_id                  0
sku                         0
product_name                0
category                    0
sub_category                0
brand                       0
unit_price                  0
quantity                    0
discount_percentage     12897
discount_amount             0
tax                         0
shipping_cost               0
cost                        0
profit                      0
total_amount                0
payment_method              0
payment_status              0
order_status                0
delivery_method             0
warehouse                   0
seller_id                   0
seller_name             12607
coupon_code             75528
returned                    0
return_reason          100532
refund_amount               0
customer_rating         14008
review_count            14471
customer_segment            0
device_type             15588
traffic_source          13599
session_id              12427
currency                    0
sales_channel               0
dtype: int64

In [14]:
# Fill missing records in phone number

df["phone_number"] = df["phone_number"].fillna("Not Provided")

In [15]:
# Fill missing records in the discount percentage column

original_value = df["quantity"] * df["unit_price"]

discount_percentage = (df["discount_amount"] / original_value) * 100

mask = (
    df["discount_percentage"].isna()
    
    & (original_value > 0)
    
    & (df["discount_amount"].notna())
)

# Update only missing discount percentage values

df.loc[mask, "discount_percentage"] = discount_percentage[mask]

In [16]:
#fill missing values in the seller name

# Create mapping from existing seller records
seller_mapping = (
    
    df.dropna(subset=["seller_name"])
      
      .drop_duplicates("seller_id")
      
      .set_index("seller_id")["seller_name"]
)

# Fill missing seller_name using seller_id lookup

df["seller_name"] = df["seller_name"].fillna(df["seller_id"].map(seller_mapping))

In [17]:
# Fill missing values in return reason 

df["returned"] = (
    df["returned"]
    .str.strip()
    .str.title()
)

mask = (
        
        (df["returned"] == "Yes")
        
        & (df["return_reason"].isna())
        
)

df.loc[mask,"return_reason"] = "Unknown"


mask = (
        
        (df["returned"] == "No")
        
        & (df["return_reason"].isna())
        
)

df.loc[mask,"return_reason"] = "Not Returned"

In [18]:
# Fill missing records in the Review count colunm

df["review_count"] = df["review_count"].fillna(0)

In [19]:
# Fill missing records in device_type, trafic_source and session_id column

columns = ["device_type","traffic_source","session_id"]

for col in columns:
    
    df[col] = df[col].fillna("Unknown")

In [20]:
# Verify missing records

df.isnull().sum()

order_id                   0
customer_id                0
customer_name              0
gender                     0
age                        0
email                      0
phone_number               0
country                    0
state                      0
city                       0
postal_code            13631
registration_date          0
order_date                 0
shipping_date          23723
delivery_date          26700
product_id                 0
sku                        0
product_name               0
category                   0
sub_category               0
brand                      0
unit_price                 0
quantity                   0
discount_percentage        0
discount_amount            0
tax                        0
shipping_cost              0
cost                       0
profit                     0
total_amount               0
payment_method             0
payment_status             0
order_status               0
delivery_method            0
warehouse                  0
seller_id                  0
seller_name                0
coupon_code            75528
returned                   0
return_reason              0
refund_amount              0
customer_rating        14008
review_count               0
customer_segment           0
device_type                0
traffic_source             0
session_id                 0
currency                   0
sales_channel              0
dtype: int64

Handle duplicates records

In [21]:
# Find duplicate percentage

duplicates = df.duplicated().sum()

duplicate_percentage = (duplicates / len(df)) * 100

duplicate_percentage

df[df.duplicated]

,order_id,customer_id,customer_name,gender,age,email,phone_number,country,state,city,...,return_reason,refund_amount,customer_rating,review_count,customer_segment,device_type,traffic_source,session_id,currency,sales_channel
2291,ORD-8D76A62F58E8,CUST-5D9C008062,Pooja Verma,Female,36,pooja.verma567@gmail.com,+91-72672-65372,India,Karnataka,Bangalore,...,Not Returned,0.0,5.0,1.0,VIP,Desktop,Referral,SESS-804F7B46EBDEEA47,INR,Website
2755,ORD-372786A60F24,CUST-37B13C9881,Sora Watanabe,Male,44,sora.watanabe502@outlook.com,+81-45-8245-9451,Japan,Kanagawa,Yokohama,...,Not Returned,0.0,1.0,0.0,Loyal,Mobile,Direct,SESS-82C2A3325FFADADA,JPY,Mobile App
2832,ORD-7853461A61AE,CUST-BE1A3EF65E,Sarah Petit,Female,41,sarah.petit293@gmail.com,+33-6-25-52-16-32,France,Auvergne-Rhone-Alpes,Lyon,...,Not Returned,0.0,5.0,2.0,VIP,Mobile,Email,SESS-632B6CC2BC70101B,EUR,Mobile App
2876,ORD-FFB2F8BDD717,CUST-9054004B22,Elizabeth Garcia,Female,36,elizabeth.garcia318@gmail.com,+1-847-483-4276,United States,Illinois,Chicago,...,Not Returned,0.0,5.0,0.0,VIP,Mobile,Email,SESS-F1E5BEEEA9DACFC0,USD,Website
3471,ORD-E75E408DBCD9,CUST-C1FE8B8181,Grace Smith,Female,34,grace.smith154@hotmail.com,+44-113-2853-4274,United Kingdom,England,Leeds,...,Not Returned,0.0,NaN,8.0,Regular,Desktop,Unknown,SESS-9B0CB97112B55AB3,GBP,Website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109868,ORD-525FA1DBD329,CUST-E27AE1F430,Larissa Ferreira,Female,43,larissa.ferreira956@yahoo.com,+55-71-92307-2641,Brazil,Bahia,Salvador,...,Not Returned,0.0,4.0,4.0,Regular,Desktop,Organic Search,SESS-002DD28CDF64C1D1,BRL,Website
109876,ORD-9015FF6E9B8B,CUST-ED952FBFA2,Thomas Smith,Male,39,thomas.smith504@gmail.com,Not Provided,United Kingdom,England,London,...,Not Returned,0.0,5.0,0.0,Loyal,Tablet,Organic Search,SESS-8ABEC1A6EDE35C6A,GBP,Mobile App
109878,ORD-3B51050A978F,CUST-4F83FF0547,David Jones,Male,49,david.jones636@hotmail.com,+1-880-262-3022,United States,Arizona,Phoenix,...,Not Returned,0.0,4.0,3.0,Regular,Mobile,Paid Ads,SESS-0FCFABE22D74E7C7,USD,Marketplace
109880,ORD-17F71D9AE6B1,CUST-26E7BF05A0,Emma MacDonald,Female,49,emma.macdonald548@hotmail.com,+1-604-455-8717,Canada,British Columbia,Vancouver,...,Not Returned,0.0,5.0,5.0,Regular,Desktop,Social Media,SESS-A21E757050A7165D,CAD,Mobile App
109882,ORD-94E332B019F6,CUST-1C9BD0AA79,William Wilson,Male,30,william.wilson875@outlook.com,+61-7-4868-7434,Australia,Queensland,Brisbane,...,Not Returned,0.0,NaN,3.0,VIP,Mobile,Social Media,SESS-9D301BAC3DB713D5,AUD,Mobile App

In [22]:
# Drop duplicate records

df = df.drop_duplicates()

# Verify duplicated records

df.duplicated().sum()

np.int64(0)

Standarize categorical columns

In [23]:
# Make function to help in standarization

def clean(x):
    
    df[x] = df[x].str.strip().str.title()

In [24]:
# standarize gender column

clean("gender")

df["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [25]:
# Standarize Country and state column

columns = ["customer_name","country","state",
           "product_name","warehouse","seller_name",
           "return_reason","device_type","traffic_source"]

for col in columns:
    
    clean(col)

In [26]:
# Standardize category column

clean("category")

df["category"].unique()

array(['Groceries', 'Fashion', 'Electronics', 'Office Supplies', 'Books',
       'Sports', 'Health', 'Beauty', 'Automotive', 'Home & Kitchen',
       'Pet Supplies', 'Garden', 'Baby Products', 'Furniture', 'Jewelry'],
      dtype=object)

In [27]:
# Stanardize sub_category column

clean("sub_category")

df["sub_category"].unique()

array(['Beverages', 'Staples', 'Shoes', "Men'S Clothing", 'Headphones',
       'Laptops', 'Printers', 'Accessories', 'Stationery', 'Academic',
       'Team Sports', 'Medical Devices', "Women'S Clothing", 'Makeup',
       'Bags', 'Car Accessories', 'Small Appliances', 'Food', 'Skincare',
       'Cookware', 'Fitness Equipment', 'Fiction', 'Snacks', 'Cameras',
       'Children', 'Tools', 'Bedding', 'Smartwatches', 'Vitamins',
       'Haircare', 'Diapers', 'Living Room', 'Fitness Trackers',
       'Non-Fiction', 'Rings', 'Smartphones', 'Toys', 'Tablets',
       'Tyres & Wheels', 'Watches', 'Outdoor', 'Outdoor Gear', 'Office',
       'Necklaces', 'Grills'], dtype=object)

In [28]:
# Standarize brand column

clean("brand")

df["brand"].unique()

array(['Unilever', "Kellogg'S", 'Nike', "Levi'S", 'Sony', 'Apple',
       'Adidas', 'Hp', 'Ray-Ban', 'Staples', 'Independent Press', 'Dell',
       'Parker', 'Yonex', 'Omron', 'Zara', 'Maybelline', 'Michael Kors',
       'Bosch', 'Philips', 'Pedigree', 'Nivea', 'Tefal', 'Decathlon',
       'Harpercollins', 'Cuisinart', 'Pepsico', 'Whiskas', 'Canon',
       'Nestle', 'The Ordinary', 'Scholastic', 'Fiskars', "L'Oreal",
       'Ikea', 'Centrum', 'Dove', 'Pampers', 'Fitbit', 'Penguin',
       'Instant Pot', 'Pandora', 'Kong', 'Samsung', 'Castrol',
       'Black+Decker', 'Huggies', 'Wilson', 'Michelin', 'Fisher-Price',
       'Fossil', 'Homecraft', 'Under Armour', 'Wayfair Basics',
       'Swarovski', 'Weber', 'Ashley', '3M'], dtype=object)

In [29]:
# Standarize payment_method column

clean("payment_method")

df["payment_method"].unique()

array(['Credit Card', 'Paypal', 'Debit Card', 'Bank Transfer',
       'Digital Wallet', 'Cash On Delivery'], dtype=object)

In [30]:
# Standardize payment status column

clean("payment_status")

df["payment_status"].unique()

array(['Cancelled', 'Paid', 'Refunded', 'Pending', 'Failed'], dtype=object)

In [31]:
# Standardize order_status column

clean("order_status")

df["order_status"].unique()

array(['Cancelled', 'Delivered', 'Processing', 'Returned', 'Shipped'],
      dtype=object)

In [32]:
# Standardize delivery method column

clean("delivery_method")

df["delivery_method"].unique()

array(['Standard', 'Express', 'Same-Day', 'Pickup'], dtype=object)

In [33]:
# Standarize customer_segment column

clean("customer_segment")

df["customer_segment"].unique()

array(['Loyal', 'Regular', 'Vip'], dtype=object)

Validate and correct invalid values

In [34]:
# Validate age column

invalid_age = df[(df["age"] < 0) | (df["age"] > 100)]

invalid_age.head()

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [35]:
# Validate unit price column

df[df["unit_price"] <= 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [36]:
# Validate quantity column

df[df["quantity"] <= 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [37]:
# Validate cost column

df[df["cost"] < 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [38]:
# validate Invalid shipping cost

df[df["shipping_cost"] < 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [39]:
# Validate invalid tax 

df[df["tax"] < 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [40]:
# Validate discount percentage column

invalid_discount_percentage = df[(df["discount_percentage"] < 0) | (df["discount_percentage"] > 100)]

invalid_discount_percentage.head()

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [41]:
# validate discount amount

df[df["discount_amount"] < 0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [42]:
# Validate total amount column

invalid_total_amount = df[df["total_amount"] < 0]

invalid_total_amount = df[(df["payment_status"] == "paid") & (df["total_amount"] == 0)]

invalid_total_amount

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

In [43]:
# Validate refund amount column

invalid_refund_amount = df[df["refund_amount"] < 0]

invalid_refund_amount.head()

invalid_refund_amount = df[(df["returned"] == "No") & (df["refund_amount"] > 0)]

invalid_refund_amount.head()

invalid_refund_amount = df[(df["returned"] == "Yes") & (df["refund_amount"] == 0)]

invalid_refund_amount.head()

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, email, phone_number, country, state, city, postal_code, registration_date, order_date, shipping_date, delivery_date, product_id, sku, product_name, category, sub_category, brand, unit_price, quantity, discount_percentage, discount_amount, tax, shipping_cost, cost, profit, total_amount, payment_method, payment_status, order_status, delivery_method, warehouse, seller_id, seller_name, coupon_code, returned, return_reason, refund_amount, customer_rating, review_count, customer_segment, device_type, traffic_source, session_id, currency, sales_channel]
Index: []

[0 rows x 49 columns]

age
unit_price
quantity
discount_percentage
discount_amount
shipping_cost
tax
cost
profit
total_amount
refund_amount

Handle Outliers

In [44]:
# Make function to detect outliers

def detect_outlier(x):
    
   Q1 = df[x].quantile(0.25)
   
   Q3 = df[x].quantile(0.75)
   
   IQR = Q3 - Q1
   
   Lower_bound = Q1 - (1.5 * IQR)
   
   Upper_bound = Q3 + (1.5 * IQR)
   
   outlier = df[(df[x] < Lower_bound) | (df[x] > Upper_bound)]
   
   return outlier

# Make function to remove outlier

def remove_outlier(x):
    
   Q1 = df[x].quantile(0.25)
   
   Q3 = df[x].quantile(0.75)
   
   IQR = Q3 - Q1
   
   Lower_bound = Q1 - (1.5 * IQR)
   
   Upper_bound = Q3 + (1.5 * IQR)
   
   clean_df = df[(df[x] >= Lower_bound) & (df[x] <= Upper_bound)]
   
   return clean_df

In [45]:
# Detect outlier in age column

outlier = detect_outlier("quantity")

outlier["quantity"].head()

44     8
68     8
70     8
147    8
246    8
Name: quantity, dtype: int64

In [46]:
# Detect oulier in discount amount column

outlier = detect_outlier("discount_amount")

outlier["discount_amount"].head()

4     115.07
8      24.00
15    822.75
23     79.49
29     82.84
Name: discount_amount, dtype: float64

In [47]:
# Detect outlier in tax column

outlier = detect_outlier("tax")

# Investigate outlier in tax column

outlier[["tax","quantity","total_amount"]].head()

df["tax"].describe()

count    103711.000000
mean         50.035756
std         134.984826
min           0.140000
25%           2.220000
50%           8.680000
75%          35.110000
max        3567.020000
Name: tax, dtype: float64

In [48]:
# Detect outlier in cost column 

outlier = detect_outlier("cost")

outlier["cost"].head()

# Investigate outliers

outlier[["unit_price","quantity","cost"]].head(10)

    unit_price  quantity     cost
5      1769.94         2  1953.07
6       154.85         6   299.06
11     1207.52         4  2984.90
12      284.77         3   409.25
15     1371.25         3  2556.97
23      132.49         6   276.71
39     1348.58         3  2466.43
42      233.36         5   389.57
48      292.81         4   394.48
50     1011.69         3  1634.67

In [49]:
# Detect outlier in profit column

outlier = detect_outlier("profit")

outlier["profit"].head()

# Investigate outliers

outlier[["unit_price","quantity","total_amount","profit"]].head(10)

    unit_price  quantity  total_amount   profit
5      1769.94         2       3805.37  1586.81
6       154.85         6        998.78   630.04
11     1207.52         4       5651.19  1845.18
12      284.77         3        999.54   445.06
15     1371.25         3       3949.20   734.03
23      132.49         6        769.11   438.74
39     1348.58         3       4005.29  1174.74
41      168.46         4        667.11   382.14
42      233.36         5       1219.31   718.89
48      292.81         4       1393.78   776.76

In [50]:
# Detect outlier in total amount column

outlier = detect_outlier("total_amount")

outlier["total_amount"].head()

# Investigae outlier

outlier[["unit_price","quantity","cost","total_amount"]].head()

    unit_price  quantity     cost  total_amount
5      1769.94         2  1953.07       3805.37
6       154.85         6   299.06        998.78
11     1207.52         4  2984.90       5651.19
12      284.77         3   409.25        999.54
15     1371.25         3  2556.97       3949.20

In [51]:
# Load clean dataset to csv file

import os

os.chdir(r"d:\my multiple projects\end to end ecomerce sales project")

df.to_csv("ecommerce_cleaned_dataset.csv", index = False)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully